version: 0.0.3
color: "red"
management:
  server:
    port: 8081
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: 'info,health,prometheus'
      base-path: /
      path-mapping:
        health: healthz
        prometheus: metrics